### ISSUE TITLE
Take home rewrite (Planet) with Angular 4+

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/take-home#153]
Look into the possibility of using Angular to rewrite the take-home mobile application. 

- https://ionicframework.com/framework

- https://www.nativescript.org/nativescript-is-how-you-build-native-mobile-apps-with-angular

**Comment by kylemathias** [comment]
I would like this just from a stand point of how widely used angular is.

**Comment by leomaxi** [comment]
Already started https://github.com/ole-vi/takeout
