### ISSUE TITLE
Apply New UI

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/take-home#60]
Modify the current UI to reflect the agreed  / approved UI.

![0](https://user-images.githubusercontent.com/2836302/26948547-cc1619c4-4c64-11e7-823a-645a0809ba42.png)
![2a](https://user-images.githubusercontent.com/2836302/26948558-d6ef421c-4c64-11e7-99e4-73322bcf0ffd.jpg)
![3b](https://user-images.githubusercontent.com/2836302/26948568-dfad8396-4c64-11e7-9795-e72063951d6c.jpg)
![2b](https://user-images.githubusercontent.com/2836302/26948581-e5416c50-4c64-11e7-8b96-9596f1baaf52.png)

**Comment by leonardmensah** [comment]
![0](https://user-images.githubusercontent.com/2836302/26948547-cc1619c4-4c64-11e7-823a-645a0809ba42.png)
![2a](https://user-images.githubusercontent.com/2836302/26948558-d6ef421c-4c64-11e7-99e4-73322bcf0ffd.jpg)
![3b](https://user-images.githubusercontent.com/2836302/26948568-dfad8396-4c64-11e7-9795-e72063951d6c.jpg)
![2b](https://user-images.githubusercontent.com/2836302/26948581-e5416c50-4c64-11e7-8b96-9596f1baaf52.png)
