### ISSUE TITLE
Spelling Mistakes in takeHomeInternDayToDay.md

### ISSUE THREAD

**Issue by Loshi93** [open-learning-exchange/take-home#77]
I was going through the steps in Take Home project. While I was reading first page I found some spelling mistakes.
![image](https://user-images.githubusercontent.com/24893117/28641583-a2d2bd7c-7204-11e7-981f-a69102ccfa35.png)

**Comment by kylemathias** [comment]
go ahead and fix it when you can.

**Comment by Loshi93** [comment]
@kylemathias Thank you. I will create a PR for this issue

**Comment by Yurockkk** [comment]
Hi @Loshma93 I think it's better to raise the issue in its own repository. That will be more clearer and allow reviewer to close the issue automatically by using keywords.
