### ISSUE TITLE
take-home app crashes on launch

### ISSUE THREAD

**Issue by Yurockkk** [open-learning-exchange/take-home#79]
App: [take-home_24-07-2017](https://drive.google.com/file/d/0Bw7aA5bLT2P9dVhOLVhuVmFXdVE/view)
Device: [HTC Butterfly](http://www.gsmarena.com/htc_butterfly-5118.php), Android version: 4.4.2, API: 19

![screenshot_2017-07-26-15-57-18](https://user-images.githubusercontent.com/11954766/28642190-7e611b3a-721f-11e7-8367-081185288135.png)

I deleted previous take-home app and restarted my phone before installing the take-home apk. take-home app crashes on launch.

**Comment by timecomplexity** [comment]
I came across the same problem.

[HP 10 tablet](http://www.gsmarena.com/hp_10_plus-6811.php)
Android 4.4.2

**Comment by leomaxi** [comment]
We will have to take a second look at background service.. On open, the app tries to run a background service.. I think that might be the problem

**Comment by kylemathias** [comment]
Same thing happening on my device
[Galaxy S4](http://www.gsmarena.com/samsung_i9500_galaxy_s4-5125.php)
Android 5.0.1

**Comment by kylemathias** [comment]
I tried installing the apk's that are dependent for emulator to run the app. it still crashes on log in.
